"""Generate PROJECT_STATUS.md and PROJECT_COMPLETION_REPORT.md from saved artefacts.

    python -m pytest tests -p no:cacheprovider > results/metrics/test_results.txt
    python scripts/build_status.py

Every number is read from experiment / result files; nothing is typed in by hand.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
E = ROOT / "experiments"
T = ROOT / "results" / "tables"
M = ROOT / "results" / "metrics"
EXCLUDE_DIRS = {".venv", "__pycache__", ".pytest_cache", ".ipynb_checkpoints", "third_party", "raw", "processed"}


def load(p: Path):
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def pct(x) -> str:
    return "–" if x is None else f"{100 * x:.1f} %"


def metrics_row(label: str, d: Path, split: str = "dev") -> str | None:
    m = load(d / f"{split}_metrics.json")
    if not m:
        return None
    return f"| {label} | {split} | {pct(m['exact_match'])} | {pct(m.get('execution_accuracy'))} | {pct(m.get('sql_validity'))} | {pct(m.get('grammar_validity'))} | `{d.relative_to(ROOT).as_posix()}/{split}_metrics.json` |"


def file_inventory() -> list[str]:
    out = []
    for p in sorted(ROOT.rglob("*")):
        rel = p.relative_to(ROOT)
        if any(part in EXCLUDE_DIRS for part in rel.parts[:-1]) or rel.parts[0] in {".venv", "third_party"}:
            continue
        if rel.parts[:2] in (("data", "raw"), ("data", "processed")):
            continue
        if p.is_file() and not p.name.endswith((".pyc",)) and "egg-info" not in str(rel) and p.suffix != ".zip":
            size = p.stat().st_size
            out.append(f"{rel.as_posix()}  ({size / 1e6:.1f} MB)" if size > 1e6 else rel.as_posix())
    return out


def test_summary() -> str:
    p = M / "test_results.txt"
    if not p.exists():
        return "_(test log not found — run `python -m pytest tests -p no:cacheprovider > results/metrics/test_results.txt`)_"
    txt = p.read_text(encoding="utf-8", errors="replace")
    m = re.findall(r"=+ (.*(?:passed|failed).*) =+", txt) or re.findall(r"(\d+ passed.*)", txt)
    return f"`{m[-1].strip()}` (full log: `results/metrics/test_results.txt`)" if m else "_(no pytest summary line found)_"


def main() -> None:
    reg = __import__("yaml").safe_load((ROOT / "configs" / "experiments.yaml").read_text(encoding="utf-8"))
    group_dir = {"main": "full_model", "baseline": "baseline", "ablation": "ablations", "scaling": "scaling"}
    exp_rows, missing = [], []
    for e in reg["experiments"]:
        d = E / group_dir[e["group"]] / e["name"]
        r = metrics_row(f"{e.get('ablation_id', '') or ''} {e['label']}".strip(), d)
        if r:
            exp_rows.append(r)
        else:
            missing.append(e["name"])
    extra = [
        ("Final model (BERT-medium, 40 epochs)", E / "full_model" / "final", "dev"),
        ("Final model (BERT-medium, 40 epochs)", E / "full_model" / "final", "test"),
        ("FULL, seed 43 (variance run)", E / "full_model" / "full_seed43", "dev"),
        ("Final model, beam 5", E / "full_model" / "final", "dev_beam5"),
    ]
    for label, d, split in extra:
        r = metrics_row(label, d, split)
        if r:
            exp_rows.append(r)
        else:
            missing.append(f"{d.name}:{split}")
    ckpts = []
    for p in sorted(E.rglob("best.pt")):
        rel = p.relative_to(ROOT).as_posix()
        ckpts.append(f"| `{rel}` | {p.stat().st_size / 1e6:.0f} MB | {'yes' if rel in ZIP_CHECKPOINTS else 'no (re-create with the logged command)'} |")
    cross = []
    for name in ("full", "final", "final_test"):
        c = load(M / f"official_crosscheck_{name}.json")
        if c:
            cross.append(f"| {name} | {c['n']:,} | {100 * c['ours_exact_match']:.2f} % | {100 * c['official_exact_match']:.2f} % | {100 * c['em_agreement']:.1f} % | "
                         + (f"{100 * c['exec_agreement']:.1f} % |" if c.get("exec_agreement") is not None else "– |"))
    orch = (E / "orchestrator.log").read_text(encoding="utf-8") if (E / "orchestrator.log").exists() else ""
    status = f"""# Project status

Generated by `scripts/build_status.py` from saved artefacts. All percentages below are **our
measurements** read from the listed files.

## What was completed

* **Implementation** (all in `src/ratsql/`, exercised by the test suite): Spider loading / validation
  and deterministic preprocessing; Spider-SQL parser; ASDL grammar, AST, transition system with grammar
  masks; SQL serializer; schema model, explicit `SchemaGraph`, `RelationVocabulary` (43 types + coarse
  6), `RelationMatrixBuilder`; n-gram and database-value schema linking; value candidates; BERT and
  BiLSTM input encoders (long-schema chunking); relation-aware transformer (efficient + reference
  implementation, vanilla mode); grammar-constrained LSTM AST decoder with memory-aligned column / table
  pointers and a value pointer (batched teacher forcing, batched greedy, beam search); trainer (AMP with
  float32 pointer mixture, accumulation, clipping, warm-up / decay, checkpoint / resume, early stopping,
  non-finite-loss monitoring); evaluation (exact match re-implementation, execution accuracy, SQL validity,
  components, hardness, complexity); analyses (error taxonomy, clause accuracy, complexity, linking,
  attention, synthetic relation task, FK join inference); inference CLI.
* **Data**: Spider 1.0 downloaded from the official link and validated (train 8,659 / dev 1,034 / test
  2,147); database-disjoint train / val / dev / test splits; synthetic Spider-format sample data.
* **Experiments**: see the table below (training runs, evaluations, analyses).
* **Documentation**: `README.md`, `reports/RAT_SQL_REPORT.md`, `reports/methodology.md`,
  `reports/experiment_results.md`, `reports/error_analysis.md`, `reports/resume_bullets.md`, executed
  notebooks in `notebooks/`.

## Tests

{test_summary()}

## Measured results

| Experiment | Split | Exact Match | Execution Accuracy | Executable SQL | Well-formed AST | Source |
|---|---|---|---|---|---|---|
""" + "\n".join(exp_rows) + f"""

### Official Spider evaluator cross-check (`results/metrics/official_crosscheck_*.json`)

| Predictions | Examples | EM (ours) | EM (official) | EM agreement | EX agreement |
|---|---|---|---|---|---|
""" + "\n".join(cross) + f"""

Further measured tables: `results/tables/ablation_results.md` (with paired-bootstrap CIs),
`scaling_results.md`, `seed_variance.md`, `hardness_results.md`, `clause_accuracy.md`,
`complexity_results.md`, `error_distribution.md`, `join_inference.md`, `attention_relation_lift.md`,
`synthetic_relation_experiment.md`, `compute_results.md`, and the per-failure
`error_analysis_full.csv`.

## Experiments performed

* 1 calibration run (`experiments/sanity/small_8ep`, used only to choose the budget; not reported).
* Controlled registry (`configs/experiments.yaml`, BERT-small, 20 epochs, seed 42): FULL, baselines A / B /
  C, ablations C / D / E / G / H / I / K, direct-pointer grammar pair H2-ref / H2, data scaling 1 / 5 / 10 / 25
  / 50 %.
* Final model (`configs/full.yaml`, BERT-medium, 40 epochs), evaluated once on Spider dev and test;
  beam-search (k = 5) evaluation on dev.
* Second seed of the controlled FULL model (seed 43).
* DEBUG mode on the synthetic dataset (`experiments/debug/rat_debug`).
* Analyses: official-evaluator cross-checks, error taxonomy (+ 30 hand-read random failures), clause /
  complexity / hardness breakdowns, schema-linking statistics, attention lift (RAT vs vanilla), synthetic
  relation task (3 seeds × 2 tasks × 2 encoders, 1,500 and 3,000 steps), FK join-inference re-serialisation,
  fp16 numerical diagnosis.
* Superseded: a first round of FULL / baseline A / baseline B runs affected by the fp16 pointer
  underflow (kept in `experiments/superseded_fp16_pointer/`, not used in any table).

## Checkpoints

| Checkpoint | Size | In the ZIP |
|---|---|---|
""" + "\n".join(ckpts) + f"""

`best.pt` files contain the model weights and the resolved config (no optimizer state); every one can be
re-created with `python scripts/train.py --config <run>/config.json`-equivalent commands recorded in
`experiments/queue.log` and each run's `config.json`. `last.pt` files (optimizer state, for resuming) are
kept on disk but excluded from the ZIP.

## Final commands

```bash
python scripts/download_data.py --dataset all
python scripts/preprocess.py --config configs/small.yaml --oracle-exec
python scripts/preprocess.py --config configs/debug.yaml
python -m pytest tests
python scripts/run_ablation.py                                            # baselines, ablations, scaling
python scripts/train.py --config configs/full.yaml --eval-splits dev test  # final model
python scripts/train.py --config configs/small.yaml --set seed=43 --output-dir experiments/full_model/full_seed43 --eval-splits dev
python scripts/evaluate.py --checkpoint experiments/full_model/final/best.pt --split dev --beam-size 5
python scripts/run_synthetic_relation_experiment.py --steps 3000
python scripts/download_data.py --dataset none --official-eval
python scripts/run_analyses.py                                            # tables, errors, joins, attention, cross-checks, notebooks
python scripts/build_report.py && python scripts/build_status.py
```

## Known limitations

See `README.md` §9 and `reports/RAT_SQL_REPORT.md` §25: single-seed ablations (one extra FULL seed),
BERT-small / BERT-medium and short training budgets instead of the paper's BERT-large / 90k steps,
execution accuracy on the original databases (not test suites), simplified lemmatisation and bounded
value index, no schema-consistency constraint during decoding, wall-clock timings on a shared laptop.

## Genuinely unavailable / not done

""" + ("* Missing measurements: " + ", ".join(missing) + "\n" if missing else "* All planned measurements are present.\n") + """* No BERT-large or 90k-step training (does not fit the 6 GB GPU / time budget); no test-suite (distilled
  database) execution accuracy; no multi-seed repetition of every ablation.

## Orchestration log

```
""" + orch.strip() + "\n```\n"
    (ROOT / "PROJECT_STATUS.md").write_text(status, encoding="utf-8")
    inventory = file_inventory()
    completion = status.replace("# Project status", "# Project completion report", 1) + f"""
## Final architecture

```
question + schema -> schema graph -> schema linking -> relation matrix (43 types)
question + schema -> BERT -> relation-aware transformer (4 layers) -> LSTM AST decoder (grammar masks,
column / table / value pointers) -> AST -> SQL -> re-parse -> execution -> EM / EX / validity
```

## Complete file list ({len(inventory)} files; excludes .venv, data/raw, data/processed, third_party, caches)

```
""" + "\n".join(inventory) + "\n```\n"
    (ROOT / "PROJECT_COMPLETION_REPORT.md").write_text(completion, encoding="utf-8")
    print(f"wrote PROJECT_STATUS.md and PROJECT_COMPLETION_REPORT.md ({len(exp_rows)} result rows, {len(inventory)} files); missing: {missing}")


ZIP_CHECKPOINTS = {"experiments/full_model/final/best.pt", "experiments/full_model/full/best.pt"}

if __name__ == "__main__":
    main()
